Vagrant.configure("2") do |config|
  pubkey = File.read(File.expand_path("./ssh-keys/id_rsa.pub"))
  
  # Create 3 VMs
  (1..3).each do |i|
    config.vm.define "web#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "web#{i}"
      
      node.vm.network "private_network", ip: "192.168.56.1#{i}"
      node.vm.network "forwarded_port", guest: 80, host: "80#{i}0"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "web#{i}"
        vb.memory = "1024"
        vb.cpus = 1
      end
      
      node.vm.provision "shell", inline: <<-SHELL
        mkdir -p /home/vagrant/.ssh
        echo "#{pubkey}" >> /home/vagrant/.ssh/authorized_keys
        chown -R vagrant:vagrant /home/vagrant/.ssh
        chmod 700 /home/vagrant/.ssh
        chmod 600 /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end